name: "Cargo Cache"
description: "Cache Cargo dependencies and build outputs"
inputs:
  tag:
    description: Cargo cache tag
    required: true
    default: default
  upload-chunk-size:
    description: "The chunk size used to split up large files during upload, in bytes"
    required: false
outputs:
  cache-hit:
    description: 'A boolean value to indicate an exact match was found for the primary key'
runs:
  using: node16
  main: dist/run/index.js
  post: dist/post/index.js
  post-if: success()
