name: "Cargo Cache"
description: "Cache Cargo dependencies and build outputs"
inputs:
  tag:
    description: Cargo cache tag
    required: true
    default: default
  upload-chunk-size:
    description: "The chunk size used to split up large files during upload, in bytes"
    required: false
runs:
  using: node16
  main: restore.mjs
  post: save.mjs
  post-if: success()
