name: Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install minimal stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Cargo dependencies and build outputs
        uses: ./
        with:
          tag: test
