name: Action

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolkit
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Cargo dependencies and build outputs
        uses: ./
        with:
          tag: test
          path: dist

  test_uncached:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolkit
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Cargo dependencies and build outputs
        uses: ./
        with:
          tag: uncached-${{ github.sha }}
          path: dist
